version: '1'
services:
  angular:
    build:
      context: ./lukather-discography-angular
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ./lukather-discography-angular:/home/app
    working_dir: /home/app
