version: '2'
services:
  db:
    image: postgres:9.4
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  rails:
    build:
      context: ./lukather-api
    command: bash /app/start_server.sh
    environment:
      RAILS_PORT: 3000
      DB_HOST: db
      DB_USERNAME: postgres
    volumes:
      - ./lukather-api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
